### ISSUE TITLE
Adapting Pokemon Showdown

### ISSUE THREAD

**Issue by aed3** [aed3/poke-sim#1]
This is a list of functions in the two Pokemon Showdown folders this project is adapting ([sim](https://github.com/smogon/pokemon-showdown/tree/master/sim) and [dex](https://github.com/smogon/pokemon-showdown/tree/master/dex)) that will, should, and might have its logic completely changed. The functions are also listed for their main reason for changing. To discuss a function in depth, a separate issue can be created directly from this list. I'll be editing this list as ideas change.

# Priority 1 (Will Change)
- [x] #3
- [x] Battle.toJSON/fromJSON [Performance] (copying battle states was resolved by #2)
- [x] PRNG.sample [Functionality] (resolved by #2)
- [x] #2
- [x] Battle.speedSort [Functionality]
- [x] #6
- [x] Battle.randomizer [Functionality] (resolved by #2)
- [x] #7
- [x] Battle.go [Functionality] (resolved by #2)
- [x] #5
- [x] #4

# Priority 2 (Should Change)
- [x] BattleQueue.resolveAction [Performance]
- [x] BattleActions.useMove (and helper functions) [Performance][Functionality]
- [x] Dex___.getByID [Performance]
- [x] Pokemon.calculateStat/getStat [Performance]
- [x] Battle.boost [Performance][Functionality]
- [x] Battle.spreadDamage [Performance][Functionality]
- [ ] Side.chooseMove [Functionality]
- [ ] Side.chooseSwitch [Functionality]
- [ ] Side.chooseTeam [Functionality]
- [ ] Battle.start [Functionality]

# Priority 3 (Might Change)
- [ ] ModdedDex.getEffectiveness [Performance][Functionality]
- [ ] Pokemon.transformInto [Performance][Functionality]
- [x] Pokemon.setStatus [Performance]
- [ ] Pokemon.addVolatile [Performance]
- [ ] Pokemon.effectiveWeather [Performance]
- [ ] Pokemon.runEffectiveness [Performance]
- [ ] Pokemon.runImmunity [Performance]
- [ ] Pokemon.runStatusImmunity [Performance]
- [ ] Pokemon.transformInto [Functionality]

**Comment by aed3** [comment]
With all the Priority 1 functions planned out, it's time to start working on the vertical slice!
